version: '2.4'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=django
      - POSTGRES_USER=root
      - POSTGRES_DB=django
    ports:
      - "5432:5432"
    volumes:
      - "./volumes/postgres/data:/var/lib/postgresql/data"