version: "3.8"
services:
  ddclient:
    image: linuxserver/ddclient:version-v3.9.1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    volumes:
      - ./config/ddclient:/config
  caddy:
    image: caddy:2
    environment:
      - TZ=Asia/Singapore
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/caddy:/config
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy:/data
      - ./app/public_html:/usr/share/caddy
