version: "3.8"
services:
  ddclient:
    image: ghcr.io/linuxserver/ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    volumes:
      - ./config/ddclient:/config
