version: "3.8"
services:
  caddy:
    image: caddy:2
    environment:
      - TZ=Asia/Singapore
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/caddy:/config
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy:/data
      - ./app/public_html:/usr/share/caddy
