cluster.name: example-staging
node.name: opensearch-data-staging
node.roles: [ master, data, ingest ]
# discovery.type: single-node
discovery.seed_hosts: [ "10.148.15.209" ]
network.host: 0.0.0.0 # required if not using the demo security configuration
network.publish_host: 10.148.0.51
bootstrap.memory_lock: true

# path.repo: ["/usr/share/opensearch/snapshots"]
plugins.security.disabled: true
# plugins.security.allow_default_init_securityindex: true
# plugins.security.advanced_modules_enabled: true
# plugins.security.roles_mapping_resolution: MAPPING_ONLY

# plugins.security.ssl_only: false
# plugins.security.ssl.http.enabled: false
# plugins.security.ssl.http.enable_openssl_if_available: false
# plugins.security.ssl.transport.enabled: false
# plugins.security.ssl.transport.enable_openssl_if_available: false